import { Capacitor } from "@capacitor/core";
export const isNative=()=>Capacitor.isNativePlatform();
const DAILY_ID=5001;
const RUN_ID_BASE=6100;
export async function nativeEnableReminder(time,message){if(!isNative())return false;const {LocalNotifications}=await import("@capacitor/local-notifications");const perm=await LocalNotifications.requestPermissions();if(perm.display!=="granted")return false;const [hour,minute]=String(time||"18:00").split(":").map(Number);await LocalNotifications.cancel({notifications:[{id:DAILY_ID}]});await LocalNotifications.schedule({notifications:[{id:DAILY_ID,title:"Stride · run reminder",body:message||"Time to lace up — you've got a session today.",schedule:{on:{hour,minute},allowWhileIdle:true,repeats:true}}]});return true;}
export async function nativeUpdateReminder(time,message){if(!isNative())return;await nativeEnableReminder(time,message);}
export async function nativeDisableReminder(){if(!isNative())return;const {LocalNotifications}=await import("@capacitor/local-notifications");await LocalNotifications.cancel({notifications:[{id:DAILY_ID}]});}
export async function nativeRunNotification(title,body){if(!isNative())return false;try{const {LocalNotifications}=await import("@capacitor/local-notifications");const perm=await LocalNotifications.requestPermissions();if(perm.display!=="granted")return false;await LocalNotifications.schedule({notifications:[{id:RUN_ID_BASE+Math.floor(Date.now()/1000)%100000,title,body,schedule:{at:new Date(Date.now()+150)}}]});return true;}catch{return false;}}
export async function ensureLocationPermission(){if(!isNative())return;try{const {Geolocation}=await import("@capacitor/geolocation");await Geolocation.requestPermissions();}catch{}}
export async function nativeShareBackup(json,filename){if(!isNative())return false;try{const {Filesystem,Directory,Encoding}=await import("@capacitor/filesystem");const {Share}=await import("@capacitor/share");const {uri}=await Filesystem.writeFile({path:filename,data:json,directory:Directory.Cache,encoding:Encoding.UTF8});await Share.share({title:filename,files:[uri]});return true;}catch(e){return /cancel/i.test(String(e?.message||e));}}
export async function styleStatusBar(){if(!isNative())return;try{const {StatusBar,Style}=await import("@capacitor/status-bar");await StatusBar.setStyle({style:Style.Dark});await StatusBar.setBackgroundColor({color:"#0c0d10"});}catch{}}
